<div style="margin-top:50px;">
    <?php

    echo "<h4>Customers</h4>";
    echo '<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Add Customer</button>';
    if ($customers->count() > 0) {
    ?>
        <table class="table table-bordered table-hover" id="customer">
            <thead class="thead-light">
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Address</th>
                    <th>Date created</th>
                    <th>Balance</th>
                    <th>Actions</th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                <?php foreach ($customers as $user) { ?>
                    <tr>
                        <td><?php echo $user->Id; ?></td>
                        <td><?php echo $user->Name; ?></td>
                        <td><?php echo $user->Address; ?></td>
                        <td><?php $date = date_create($user->DateCreated); echo date_format($date,"Y/m/d"); ?></td>
                        <td><?php echo round($user->Balance,2); ?></td>
                        <td><i class='fas fa-trash delete' data-name='<?php echo $user->Name; ?>' data-id='<?php echo $user->Id; ?>'></i> <i class='fas fa-edit edit' data-id='<?php echo $user->Id; ?>'></i></td>
                        <td><a href="/LindseyTest/invoices?Id=<?php echo $user->Id; ?>"  class="btn btn-small btn-warning">Invoices</a></td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    <?php
    }

    ?>
</div>

<div class="modal" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Add Customer</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="Name" class="text-light">Name:</label>
                        <input type="text" class="form-control" id="Name" placeholder="Name" name="Name">
                    </div>
                    <div class="form-group">
                        <label class="text-light">Address</label>
                        <textarea row="10" col="20" class="form-control" id="Address" placeholder="Address"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="Username" class="text-light">User Name</label>
                        <input type="text" class="form-control" id="Username" placeholder="Username" name="Username">
                    </div>
                    <div class="form-group">
                        <label for="Password" class="text-light">Password</label>
                        <input type="password" class="form-control" id="Password" placeholder="Password" name="Password">
                    </div>
                    <input type="hidden" id="Id" name="Id">
                    <button id="create" type="submit" class="btn btn-primary">Create</button>
                    <button id="update" type="submit"  class="btn btn-primary" style="display: none;">Update</button>
                </form>
            </div>
            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        $('#customer').DataTable();

        $("#create").click(function(event) {
            event.preventDefault();
            $.post("/LindseyTest/customer/Create", {
                    Name: $("#Name").val(),
                    Address: $("#Address").val(),
                    Username: $("#Username").val(),
                    Password: $("#Password").val()
                },
                function(data, status) {
                    if (data != false) {
                        $('#myModal').modal('hide');
                        alert("Customer created");
                        location.reload();
                    }
                });
        });

        $(".delete").click(function() {

            var r = confirm("Are sure you want to delete " + $(this).data('name'));
            if (r == true) {
                $.post("/LindseyTest/customer/delete", {
                    Id: $(this).data('id'),
                },
                function(data, status) {
                    alert("User deleted");
                    location.reload();
                });
            }
        });

        $(".edit").click(function() {
            $.get("/LindseyTest/customer/update", {
                    Id: $(this).data('id'),
                },
                function(data, status) {
                   for(var item in data){
                       //console.log(data[item].Name)
                       $("#Id").val(data[item].Id),
                       $("#Name").val(data[item].Name);
                       $("#Address").val(data[item].Address);
                       $("#Username").val(data[item].Username);
                       $("#Password").val(data[item].Password);
                   }

                   $('#myModal').modal('show');
                   $('#create').hide();
                   $('#update').show();

                });
        });

        $("#update").click(function(event) {
            event.preventDefault();
            $.post("/LindseyTest/customer/edit", {
                    Id: $("#Id").val(),
                    Name: $("#Name").val(),
                    Address: $("#Address").val(),
                    Username: $("#Username").val(),
                    Password: $("#Password").val()
                },
                function(data, status) {
                    if (data != false) {
                        $('#myModal').modal('hide');
                        alert("Customer Updated");
                        location.reload();
                    }
                });
        });
    });
</script>